/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLSinhVien;

import bangAdd.bangMonHocPanek;
import bangAdd.bangThongTinPanel;
//version 2121
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lebao
 */
public class QuanLySinhVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySinhVien
     */
    public QuanLySinhVien() {
        initComponents();
        this.setSize(800, 600);
        this.setTitle("QuanLySinhVien");
        this.setLocationRelativeTo(null);
        dtmInfoStudy = (DefaultTableModel) this.jTable1.getModel();
        KetNoiCSDL();
        HienThi();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        btnQLSV = new javax.swing.JButton();
        btnMonHoc = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        pChuyendoi = new javax.swing.JPanel();
        pQLSV = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtGioitinh = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtQueQuan = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnKQHT = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        txtTK = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_QLSinhvien = new javax.swing.JMenuItem();
        menu_Monhoc = new javax.swing.JMenuItem();
        menu_thoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel13.setLayout(new java.awt.GridLayout(3, 0));

        btnQLSV.setText("Quản lý sinh viên");
        btnQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSVActionPerformed(evt);
            }
        });
        jPanel13.add(btnQLSV);

        btnMonHoc.setText("Môn Học");
        btnMonHoc.setPreferredSize(new java.awt.Dimension(100, 50));
        btnMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonHocActionPerformed(evt);
            }
        });
        jPanel13.add(btnMonHoc);

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel13.add(btnThoat);

        getContentPane().add(jPanel13, java.awt.BorderLayout.WEST);

        pChuyendoi.setLayout(new java.awt.BorderLayout());

        pQLSV.setLayout(new javax.swing.BoxLayout(pQLSV, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Sinh Viên");
        jPanel2.add(jLabel1);

        pQLSV.add(jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pQLSV.add(jPanel4);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Họ Tên:   ");
        jPanel8.add(jLabel2);

        txtHoTen.setPreferredSize(new java.awt.Dimension(150, 22));
        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });
        jPanel8.add(txtHoTen);

        jPanel6.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Ngày Sinh:");
        jPanel9.add(jLabel3);

        txtNgaySinh.setPreferredSize(new java.awt.Dimension(150, 22));
        txtNgaySinh.setRequestFocusEnabled(true);
        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        jPanel9.add(txtNgaySinh);

        jPanel6.add(jPanel9);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Giới Tính");
        jPanel12.add(jLabel4);

        txtGioitinh.setPreferredSize(new java.awt.Dimension(150, 22));
        txtGioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioitinhActionPerformed(evt);
            }
        });
        jPanel12.add(txtGioitinh);

        jPanel6.add(jPanel12);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Quê Quán:");
        jPanel14.add(jLabel5);

        txtQueQuan.setPreferredSize(new java.awt.Dimension(150, 22));
        txtQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQueQuanActionPerformed(evt);
            }
        });
        jPanel14.add(txtQueQuan);

        jPanel6.add(jPanel14);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("Mã Lớp:");
        jPanel11.add(jLabel6);

        txtMaLop.setPreferredSize(new java.awt.Dimension(150, 22));
        txtMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLopActionPerformed(evt);
            }
        });
        jPanel11.add(txtMaLop);

        jPanel7.add(jPanel11);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel9.setText("Mã Sinh Viên:");
        jPanel16.add(jLabel9);

        txtMaSV.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel16.add(txtMaSV);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel16.add(jPanel10);

        jPanel7.add(jPanel16);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel7.add(jPanel15);

        jPanel3.add(jPanel7);

        pQLSV.add(jPanel3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel18.add(btnThem);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel18.add(btnLuu);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel18.add(btnXoa);

        btnKQHT.setText("Kết Quả Học Tập");
        btnKQHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKQHTActionPerformed(evt);
            }
        });
        jPanel18.add(btnKQHT);

        jPanel1.add(jPanel18);

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel17.add(btnTimKiem);

        txtTK.setPreferredSize(new java.awt.Dimension(200, 22));
        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });
        jPanel17.add(txtTK);

        jPanel1.add(jPanel17);

        pQLSV.add(jPanel1);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Họ Tên", "Ngày Sinh", "Giới Tính", "Quê Quán", "Mã Lớp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pQLSV.add(jPanel5);

        pChuyendoi.add(pQLSV, java.awt.BorderLayout.CENTER);

        getContentPane().add(pChuyendoi, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        menu_QLSinhvien.setText("Quản lý sinh viên");
        menu_QLSinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_QLSinhvienActionPerformed(evt);
            }
        });
        jMenu1.add(menu_QLSinhvien);

        menu_Monhoc.setText("Môn Học");
        menu_Monhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_MonhocActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Monhoc);

        menu_thoat.setText("Thoát");
        menu_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_thoatActionPerformed(evt);
            }
        });
        jMenu1.add(menu_thoat);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtHoTen.setText("");
        txtNgaySinh.setText("1-1-1900");
        txtGioitinh.setText("");
        txtQueQuan.setText("");
        txtMaLop.setText("Lop A");
        txtMaSV.setText("");
        txtHoTen.requestFocus();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtMaSV.getText())) {
            JOptionPane.showMessageDialog(this, "MãSV không được để trống.");
            txtMaSV.requestFocus();
            return;
        }
        else if (KTmaSV(txtMaSV.getText())) {
            int ret = JOptionPane.showConfirmDialog(null, "Mã[" + txtMaSV.getText() + "] đã tồn tại Bạn có muốn cập nhật ?", "", JOptionPane.YES_NO_OPTION);
            if (ret == JOptionPane.NO_OPTION) {
                return;
            }
            try {
                String sqlUpdate = "update sinhvien set hoten=N'" + txtHoTen.getText() + "', ngsinh='" + txtNgaySinh.getText() + "' , gioitinh=N'" + txtGioitinh.getText() + "' , quequan=N'" + txtQueQuan.getText() + "' , malop='" + txtMaLop.getText() + "' where masv='" + txtMaSV.getText() + "' ";
                int x = statement.executeUpdate(sqlUpdate);
                if (x >= 1) {
                    HienThi();
                }
            } catch (SQLException ex) {
            
            }
            } else {
                try {

                    String sqlInsert1 = "SET DATEFORMAT DMY INSERT INTO SINHVIEN  values('" + txtMaSV.getText() + "',N'" + txtHoTen.getText() + "','" + txtNgaySinh.getText() + "',N'" + txtGioitinh.getText() + "',N'" + txtQueQuan.getText() + "','" + txtMaLop.getText() + "')";
                    int y = statement.executeUpdate(sqlInsert1);

                    if (y >= 1) {
                        HienThi();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Them sinh vien khong thanh cong.");
                }
            }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        // TODO Auto-generated method stub
        if ("".equals(txtTK.getText())) {
            HienThi();
        } else {
            try {
                PreparedStatement prestament;
                String sql2 = "select * from sinhvien where masv=? or hoten=?  or gioitinh=? or quequan=? or malop=?";
                prestament = con.prepareStatement(sql2);
                prestament.setString(1, txtTK.getText());
                prestament.setString(2, txtTK.getText());
                prestament.setString(3, txtTK.getText());
                prestament.setString(4, txtTK.getText());
                prestament.setString(5, txtTK.getText());

                result = prestament.executeQuery();
                dtmInfoStudy.setRowCount(0);
                while (result.next()) {
                    String ma = result.getString("MASV");
                    String ten = result.getString("HOTEN");
                    String ns = result.getString("NGSINH");
                    String gt = result.getString("GIOITINH");
                    String qq = result.getString("QUEQUAN");
                    String ml = result.getString("MALOP");
                    Vector<Object> vec = new Vector<Object>();
                    vec.add(ma);
                    vec.add(ten);
                    vec.add(ns);
                    vec.add(gt);
                    vec.add(qq);
                    vec.add(ml);
                    dtmInfoStudy.addRow(vec);
                }
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.NO_OPTION) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtGioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioitinhActionPerformed

    private void txtQueQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueQuanActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (KTmaSV(txtMaSV.getText())) {
            int ret = JOptionPane.showConfirmDialog(null, "Mã[" + txtMaSV.getText() + "] Bạn có muốn xóa", "", JOptionPane.YES_NO_OPTION);
            if (ret == JOptionPane.NO_OPTION) {
                return;
            }
            try {
                String sqldeletSV = "delete  from sinhvien where masv='" + txtMaSV.getText() + "' ";
                String sqldeleteKQ = "delete from ketqua where masv='" + txtMaSV.getText() + "'";
                int y = statement.executeUpdate(sqldeleteKQ);
                int x = statement.executeUpdate(sqldeletSV);
                if (x >= 1 || y >= 1) {
                    JOptionPane.showMessageDialog(this, "Xoa sinh vien thanh cong.");
                    HienThi();
                    txtHoTen.setText("");
                    txtNgaySinh.setText("");
                    txtGioitinh.setText("");
                    txtQueQuan.setText("");
                    txtMaLop.setText("");
                    txtMaSV.setText("");
                    txtHoTen.requestFocus();
                }
            } catch (SQLException ex) {
            }
        } else {
            JOptionPane.showMessageDialog(this, "Xoa sinh vien khong thanh cong.");
            txtHoTen.setText("");
            txtNgaySinh.setText("");
            txtGioitinh.setText("");
            txtQueQuan.setText("");
            txtMaLop.setText("");
            txtMaSV.setText("");
            txtHoTen.requestFocus();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = this.jTable1.getSelectedRow();
        this.txtMaSV.setText((String) jTable1.getValueAt(row, 0));
        this.txtHoTen.setText((String) jTable1.getValueAt(row, 1));
        this.txtGioitinh.setText((String) jTable1.getValueAt(row, 3));
        this.txtNgaySinh.setText((String) jTable1.getValueAt(row, 2));
        this.txtQueQuan.setText((String) jTable1.getValueAt(row, 4));
        this.txtMaLop.setText((String) jTable1.getValueAt(row, 5));
//        this.txtHocKy.setText( jTable1.getValueAt(row, 7)+"");
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnKQHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKQHTActionPerformed
        // TODO add your handling code here:
        bangThongTinPanel btt = new bangThongTinPanel();
        btt.lbHoten.setText(txtHoTen.getText());
        btt.lbGioitinh.setText(txtGioitinh.getText());
        btt.lbLop.setText(txtMaLop.getText());
        btt.lbNgaysinh.setText(txtNgaySinh.getText());
        btt.lbQueQuan.setText(txtQueQuan.getText());
        btt.lbMaSV.setText(txtMaSV.getText());
        btt.HienThiNhieuBangDiem(txtMaSV.getText());
        pChuyendoi.removeAll();
        pChuyendoi.repaint();
        pChuyendoi.validate();

        pChuyendoi.add(btt.getPBTT());
        pChuyendoi.repaint();
        pChuyendoi.validate();
    }//GEN-LAST:event_btnKQHTActionPerformed

    private void btnMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonHocActionPerformed
        // TODO add your handling code here:
        bangMonHocPanek bmh = new bangMonHocPanek();
        pChuyendoi.removeAll();
        pChuyendoi.repaint();
        pChuyendoi.validate();

        pChuyendoi.add(bmh);
        pChuyendoi.repaint();
        pChuyendoi.validate();

    }//GEN-LAST:event_btnMonHocActionPerformed

    private void btnQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSVActionPerformed
        // TODO add your handling code here:

        pChuyendoi.removeAll();
        pChuyendoi.repaint();
        pChuyendoi.validate();

        pChuyendoi.add(pQLSV);
        pChuyendoi.repaint();
        pChuyendoi.validate();
    }//GEN-LAST:event_btnQLSVActionPerformed

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKActionPerformed

    private void menu_QLSinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_QLSinhvienActionPerformed
        // TODO add your handling code here:
        pChuyendoi.removeAll();
        pChuyendoi.repaint();
        pChuyendoi.validate();

        pChuyendoi.add(pQLSV);
        pChuyendoi.repaint();
        pChuyendoi.validate();
    }//GEN-LAST:event_menu_QLSinhvienActionPerformed

    private void menu_MonhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_MonhocActionPerformed
        // TODO add your handling code here:
        bangMonHocPanek bmh = new bangMonHocPanek();
        pChuyendoi.removeAll();
        pChuyendoi.repaint();
        pChuyendoi.validate();

        pChuyendoi.add(bmh);
        pChuyendoi.repaint();
        pChuyendoi.validate();
    }//GEN-LAST:event_menu_MonhocActionPerformed

    private void menu_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_thoatActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.NO_OPTION) {
            return;
        }
        System.exit(0);


    }//GEN-LAST:event_menu_thoatActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLopActionPerformed
    private void KetNoiCSDL() {
        String strServer = "TOSHIBA-C855";
        String strDatebase = "QLSV";
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionURL = "jdbc:sqlserver://" + strServer + ":1433;databaseName=" + strDatebase
                    + ";integratedSecurity = true";
            con = DriverManager.getConnection(connectionURL);
            statement = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

        } catch (SQLException ex1) {
            System.out.println("SQL Exception:" + ex1.toString());

        } catch (ClassNotFoundException ex2) {
            System.out.println(" Class Not Found Exception:" + ex2.toString());

        }

    }

    private void HienThi() {
        try {
            String sql = "select distinct masv,hoten,ngsinh,gioitinh,quequan,malop from SINHVIEN ";
            result = statement.executeQuery(sql);
            dtmInfoStudy.setRowCount(0);
            while (result.next()) {

                String ma = result.getString("MASV");
                String ten = result.getString("HOTEN");
                String ns = result.getString("NGSINH");
                String gt = result.getString("GIOITINH");
                String qq = result.getString("QUEQUAN");
                String ml = result.getString("MALOP");
//                int hk=result.getInt("HOCKY"); 
                Vector<Object> vec = new Vector<>();

                vec.add(ma);
                vec.add(ten);
                vec.add(ns);
                vec.add(gt);
                vec.add(qq);
                vec.add(ml);
//  

                dtmInfoStudy.addRow(vec);

            }

        } catch (SQLException ex) {

        }

    }

    public boolean KTmaSV(String ma) {
        try {
            String sqlSelect = "Select * from sinhvien where  masv='" + ma + "' ";
            ResultSet re = statement.executeQuery(sqlSelect);

            if (re.next()) {
                return true;
            } else {
                return false;
            }

        } catch (SQLException ex) {

        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySinhVien().setVisible(true);
            }
        });
    }
    private Connection con = null;
    private Statement statement = null;
    private DefaultTableModel dtmInfoStudy;
    private ResultSet result;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKQHT;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMonHoc;
    private javax.swing.JButton btnQLSV;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menu_Monhoc;
    private javax.swing.JMenuItem menu_QLSinhvien;
    private javax.swing.JMenuItem menu_thoat;
    private javax.swing.JPanel pChuyendoi;
    public javax.swing.JPanel pQLSV;
    private javax.swing.JTextField txtGioitinh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables

}
