//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _CSDLPhantan__QL_Chungcu.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TOSHIBA-SATELLI\\SQLEXPRESS;Initial Catalog=CSDLPhanTan_CUA_HANG_BAN_Q" +
            "UA_LUU_NIEM_K&T;Integrated Security=True")]
        public string CSDLPhanTan_CUA_HANG_BAN_QUA_LUU_NIEM_K_TConnectionString {
            get {
                return ((string)(this["CSDLPhanTan_CUA_HANG_BAN_QUA_LUU_NIEM_K_TConnectionString"]));
            }
        }
    }
}
