/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangAdd;

import QLSinhVien.QuanLySinhVien;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lebao
 */
public class bangThongTinPanel extends javax.swing.JPanel {

    /**
     * Creates new form bangThongTinPanel
     */
    public bangThongTinPanel() {
        initComponents();

        KetnoiCSDL();

//        BangDiemHocKy bangdiem  = new BangDiemHocKy();
        fillCombobox();
//touchCombobox();
        dtm1 = (DefaultTableModel) jTable2.getModel();
        dtm2 = (DefaultTableModel) jTable3.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBTT = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pTren = new javax.swing.JPanel();
        pTren_Trai = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbHoten = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbNgaysinh = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbGioitinh = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbQueQuan = new javax.swing.JLabel();
        pTren_Phai = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbMaSV = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbLop = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        pTxtFieldBTT = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTenMH = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDiemGKk = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtDiemCKk = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtDiemTKk = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtXepLoaii = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtHocKyy = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        btnButtonBTT = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbhocky1 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lbHK1 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lbhocky2 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lbHK2 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        btnNam1 = new javax.swing.JButton();
        btnNam2 = new javax.swing.JButton();
        btmNam3 = new javax.swing.JButton();
        btnNam4 = new javax.swing.JButton();
        btnNam5 = new javax.swing.JButton();
        btnNam6 = new javax.swing.JButton();

        pBTT.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        pTren.setLayout(new javax.swing.BoxLayout(pTren, javax.swing.BoxLayout.X_AXIS));

        pTren_Trai.setLayout(new javax.swing.BoxLayout(pTren_Trai, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Họ Tên:");
        jPanel8.add(jLabel1);

        lbHoten.setText("jLabel2");
        jPanel8.add(lbHoten);

        pTren_Trai.add(jPanel8);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Ngày Sinh:");
        jPanel9.add(jLabel3);

        lbNgaysinh.setText("jLabel4");
        jPanel9.add(lbNgaysinh);

        pTren_Trai.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Giới Tính:");
        jPanel10.add(jLabel5);

        lbGioitinh.setText("jLabel6");
        jPanel10.add(lbGioitinh);

        pTren_Trai.add(jPanel10);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText("Quê Quán:");
        jPanel12.add(jLabel7);

        lbQueQuan.setText("jLabel8");
        jPanel12.add(lbQueQuan);

        pTren_Trai.add(jPanel12);

        pTren.add(pTren_Trai);

        pTren_Phai.setLayout(new javax.swing.BoxLayout(pTren_Phai, javax.swing.BoxLayout.Y_AXIS));

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel9.setText("Mã Sinh Viên:");
        jPanel11.add(jLabel9);

        lbMaSV.setText("...");
        jPanel11.add(lbMaSV);

        pTren_Phai.add(jPanel11);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pTren_Phai.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel12.setText("Lớp:");
        jPanel14.add(jLabel12);

        lbLop.setText("jLabel13");
        jPanel14.add(lbLop);

        pTren_Phai.add(jPanel14);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pTren_Phai.add(jPanel15);

        pTren.add(pTren_Phai);

        jPanel2.add(pTren);

        jPanel21.setLayout(new java.awt.BorderLayout());

        pTxtFieldBTT.setLayout(new javax.swing.BoxLayout(pTxtFieldBTT, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Mã Môn Học:");
        jPanel4.add(jLabel2);

        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Tên MH:");
        jPanel5.add(jLabel4);

        txtTenMH.setPreferredSize(new java.awt.Dimension(150, 22));
        txtTenMH.setRequestFocusEnabled(false);
        jPanel5.add(txtTenMH);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("Điểm Giứa Kỳ:");
        jPanel6.add(jLabel6);

        txtDiemGKk.setPreferredSize(new java.awt.Dimension(150, 22));
        txtDiemGKk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemGKkActionPerformed(evt);
            }
        });
        jPanel6.add(txtDiemGKk);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setText("Điểm Cuối Kỳ:");
        jPanel7.add(jLabel8);

        txtDiemCKk.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel7.add(txtDiemCKk);

        jPanel3.add(jPanel7);

        pTxtFieldBTT.add(jPanel3);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.Y_AXIS));

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel10.setText("Điểm Tổng Kết:");
        jPanel16.add(jLabel10);

        txtDiemTKk.setPreferredSize(new java.awt.Dimension(150, 22));
        txtDiemTKk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemTKkActionPerformed(evt);
            }
        });
        txtDiemTKk.setRequestFocusEnabled(false);
        jPanel16.add(txtDiemTKk);

        jPanel17.add(jPanel16);

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel11.setText("Xếp Loại:");
        jPanel18.add(jLabel11);

        txtXepLoaii.setPreferredSize(new java.awt.Dimension(150, 22));
        txtXepLoaii.setRequestFocusEnabled(false);
        jPanel18.add(txtXepLoaii);

        jPanel17.add(jPanel18);

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel13.setText("Học Kỳ:");
        jPanel19.add(jLabel13);

        txtHocKyy.setPreferredSize(new java.awt.Dimension(150, 22));
        txtHocKyy.setRequestFocusEnabled(false);
        jPanel19.add(txtHocKyy);

        jPanel17.add(jPanel19);
        jPanel17.add(jPanel20);

        pTxtFieldBTT.add(jPanel17);

        jPanel21.add(pTxtFieldBTT, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel21);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        btnButtonBTT.add(btnThem);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        btnButtonBTT.add(btnLuu);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        btnButtonBTT.add(btnXoa);

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        btnButtonBTT.add(btnThoat);

        jPanel2.add(btnButtonBTT);

        jPanel34.setPreferredSize(new java.awt.Dimension(400, 101));
        jPanel34.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Môn Học", "Tên Môn Học", "Điểm Giữa Kỳ", "Điểm Cuối Kỳ", "Điểm Tổng Kết", "Xếp Loại"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel34.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.Y_AXIS));

        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel15.setText("Học kỳ:");
        jPanel24.add(jLabel15);

        lbhocky1.setText("1");
        jPanel24.add(lbhocky1);

        jPanel22.add(jPanel24);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel25.setLayout(flowLayout1);

        jLabel18.setText("Điểm học kỳ :");
        jPanel25.add(jLabel18);

        lbHK1.setText("...");
        jPanel25.add(lbHK1);

        jPanel22.add(jPanel25);

        jPanel34.add(jPanel22, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel34);

        jPanel35.setPreferredSize(new java.awt.Dimension(400, 101));
        jPanel35.setLayout(new java.awt.BorderLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Môn Học", "Tên Môn Học", "Điểm Giữa Kỳ", "Điểm Cuối Kỳ", "Điểm Tổng Kết", "Xếp Loại"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jPanel35.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel26.setLayout(new javax.swing.BoxLayout(jPanel26, javax.swing.BoxLayout.Y_AXIS));

        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel20.setText("Học kỳ:");
        jPanel27.add(jLabel20);

        lbhocky2.setText("2");
        jPanel27.add(lbhocky2);

        jPanel26.add(jPanel27);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        jPanel28.setLayout(flowLayout2);

        jLabel22.setText("Điểm học kỳ :");
        jPanel28.add(jLabel22);

        lbHK2.setText("...");
        jPanel28.add(lbHK2);

        jPanel26.add(jPanel28);

        jPanel35.add(jPanel26, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel35);

        btnNam1.setText("Năm 1");
        btnNam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNam1ActionPerformed(evt);
            }
        });
        jPanel23.add(btnNam1);

        btnNam2.setText("Năm 2");
        btnNam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNam2ActionPerformed(evt);
            }
        });
        jPanel23.add(btnNam2);

        btmNam3.setText("Năm 3");
        btmNam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmNam3ActionPerformed(evt);
            }
        });
        jPanel23.add(btmNam3);

        btnNam4.setText("Năm 4");
        btnNam4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNam4ActionPerformed(evt);
            }
        });
        jPanel23.add(btnNam4);

        btnNam5.setText("Năm 5");
        btnNam5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNam5ActionPerformed(evt);
            }
        });
        jPanel23.add(btnNam5);

        btnNam6.setText("Năm 6");
        btnNam6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNam6ActionPerformed(evt);
            }
        });
        jPanel23.add(btnNam6);

        jPanel2.add(jPanel23);

        pBTT.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtTenMH.setText("");
        //        txtTenMHh.setText("");
        txtHocKyy.setText("");
        txtXepLoaii.setText("");
        txtDiemGKk.setText("");
        txtDiemCKk.setText("");
        txtDiemTKk.setText("");
        txtTenMH.requestFocus();

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        System.out.println(jComboBox1.getSelectedItem());
        //ktra khi user chi update diem gk ,ck ,

        if (KTma((String) jComboBox1.getSelectedItem(), Integer.valueOf(txtHocKyy.getText()))) {
            int ret = JOptionPane.showConfirmDialog(null, "Mã[" + txtTenMH.getText() + "] tại hoc ky:" + txtHocKyy.getText() + " đã tồn tại Bạn có muốn cập nhật ?", "", JOptionPane.YES_NO_OPTION);
            if (ret == JOptionPane.NO_OPTION) {
                return;
            }
            try {
                String sqlUpdate1 = "update ketqua set diem_gk=" + txtDiemGKk.getText() + ",diem_ck=" + txtDiemCKk.getText() + ",diem_tk=" + txtDiemTKk.getText() + " where mamh='" + jComboBox1.getSelectedItem() + "' and hocky=" + txtHocKyy.getText() + " ";
                //                String sqlUpdate2="update monhoc set tenmh=N'"+jComboBox1.getSelectedItem()+"' where mamh = '"+txtMaMHh+"'";
                int x = statement.executeUpdate(sqlUpdate1);
                //                int y=statement.executeUpdate(sqlUpdate2);
                //                if(x>=1)
                HienThiNhieuBangDiem(masv);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            try {

                String sqlInsert1 = "insert into ketqua(masv,mamh,hocky,diem_gk,diem_ck,diem_tk,xeploai)  values('" + lbMaSV.getText() + "','" + jComboBox1.getSelectedItem() + "'," + txtHocKyy.getText() + "," + txtDiemGKk.getText() + "," + txtDiemCKk.getText() + "," + txtDiemTKk.getText() + ",'" + txtXepLoaii.getText() + "')";
                int x = statement.executeUpdate(sqlInsert1);
                //                   String sqlInsert2="insert into monhoc(tenmh)  values(N'"++"')";
                //                   int y=statement.executeUpdate(sqlInsert2);
                //                    if(x>=1||y>=1)
                HienThiNhieuBangDiem(masv);

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình", "Thông báo Thoát", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.NO_OPTION) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code her
        //        jComboBox1.getSelectedItem();

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if (global == 1) {

            //JOptionPane.showMessageDialog( this, mamh ,"thong bao ",JOptionPane.INFORMATION_MESSAGE);
            try {
                //String sql = "select * from monhoc where mamh = '"+mamh+"' ";
                String mamh = (String) jComboBox1.getSelectedItem();
                String sql = "select tenmh from monhoc where mamh = ?";
                //result = statement.executeQuery(sql);
                PreparedStatement preSta = con.prepareStatement(sql);
                preSta.setString(1, mamh);
                ResultSet rs = preSta.executeQuery();
                if (rs.next()) {
                    txtTenMH.setText(rs.getString(1));
                } else {
                    JOptionPane.showMessageDialog(null, "Không có môn học tồn tại");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    private void KetnoiCSDL() {
        String strServer = "TOSHIBA-C855";
        String strDatebase = "QLSV";
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionURL = "jdbc:sqlserver://" + strServer + ":1433;databaseName=" + strDatebase
                    + ";integratedSecurity = true";
            con = DriverManager.getConnection(connectionURL);
            statement = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

        } catch (SQLException ex1) {
            System.out.println("SQL Exception:" + ex1.toString());

        } catch (ClassNotFoundException ex2) {
            System.out.println(" Class Not Found Exception:" + ex2.toString());

        }
    }

    public int getHocKy(String ma) {
        int sohocky = 3;
        try {
            String sqlselect = "select count(*) from tbhocky where masv='" + ma + "' ";
            result = statement.executeQuery(sqlselect);
            sohocky = result.getInt("count(*)");

        } catch (Exception e) {
        }

        return sohocky;
    }
//    private void setTenPanel(String a){
//        for(int i = 0;i<getHocKy();i++){
//           String hocky="hocky"+i;
//           a= hocky;
//       }
//    }

    public void HienThiNhieuBangDiem(String ma) {
        HienthiCSDL(dtm1, vec1, ma, Integer.valueOf(lbhocky1.getText()));
        HienthiCSDL(dtm2, vec2, ma, Integer.valueOf(lbhocky2.getText()));
        masv = ma;
        try {
            String sqltk1 = "select sum(diem_tk)/count(*) as s from  ketqua where masv='" + ma.trim() + "'  and hocky=" + Integer.parseInt(lbhocky1.getText());
            result = statement.executeQuery(sqltk1);
            while (result.next()) {

                float diemTK1 = result.getFloat(1);

                lbHK1.setText(String.valueOf(diemTK1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {

            String sqltk2 = "select sum(diem_tk)/count(*) as s from ketqua where masv='" + ma.trim() + "'  and hocky = " + Integer.parseInt(lbhocky2.getText());
            result = statement.executeQuery(sqltk2);
            while (result.next()) {

                float diemTK2 = result.getFloat(1);

                lbHK2.setText(String.valueOf(diemTK2));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public boolean KTma(String ma, int hk) {
        try {
            String sqlSelect = "Select * from monhoc,ketqua where  monhoc.mamh=ketqua.mamh and monhoc.mamh='" + ma + "'  and hocky=" + hk + " ";
            ResultSet re = statement.executeQuery(sqlSelect);

            if (re.next()) {
                return true;
            } else {
                return false;
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
    }

    public boolean KTinfoPointStudy(String mamh, String tenmh, int hk) {
        try {
            String sqlSelect = "Select * from ketqua,monhoc where ketqua.mamh=monhoc.mamh and mamh=" + mamh + " and tenmh=N'" + tenmh + "' and hocky=" + hk + " ";
            ResultSet re = statement.executeQuery(sqlSelect);

            if (re.next()) {
                return true;
            } else {
                return false;
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
    }

    private void fillCombobox() {
        try {
            String sql = "select mamh from monhoc";
            ResultSet resultt = statement.executeQuery(sql);
            while (resultt.next()) {
                String mamh = resultt.getString("mamh");
                jComboBox1.addItem(mamh);
            }
            global = 1;
        } catch (Exception e) {
        }
    }

    public void touchCombobox() {
        String tenmh = (String) jComboBox1.getSelectedItem();
        try {
            String sql = "select mamh from monhoc where tenmh = n'?' ";
            prestatement = con.prepareStatement(sql);
            prestatement.setString(0, tenmh);
            result = prestatement.executeQuery();
            String mamh = result.getString("mamh");
            txtTenMH.setText(mamh);
        } catch (Exception e) {

        }
    }

    void HienthiCSDL(DefaultTableModel dtm, Vector<Object> vec, String ma, int hk) {

        try {
            String sql = "select ketqua.MAMH,TENMH,DIEM_GK,DIEM_CK,DIEM_TK,XEPLOAI from ketqua,monhoc where ketqua.mamh=monhoc.mamh and masv='" + ma + "'  and hocky=" + hk + " ";
            result = statement.executeQuery(sql);
            dtm.setRowCount(0);
            while (result.next()) {

                String maMH = result.getString(1);
                String tenMH = result.getString(2);
                float diemGK = result.getFloat(3);
                float diemCK = result.getFloat(4);
                float diemTK = result.getFloat(5);
                String xepLoai = result.getString(6);
                vec = new Vector<Object>();

                vec.add(maMH);
                vec.add(tenMH);
                vec.add(diemGK);
                vec.add(diemCK);
                vec.add(diemTK);
                vec.add(xepLoai);
                dtm.addRow(vec);

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
    private void txtDiemGKkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemGKkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemGKkActionPerformed

    private void txtDiemTKkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemTKkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemTKkActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        //         TouchTable(a, b, c, d, e, f);
        int row = this.jTable2.getSelectedRow();
        this.txtTenMH.setText((String) jTable2.getValueAt(row, 1));
        //        this.txtTenMHh.setText((String) jTable1.getValueAt(row, 2));
        this.txtDiemGKk.setText(jTable2.getValueAt(row, 2) + "");
        this.txtDiemCKk.setText(jTable2.getValueAt(row, 3) + "");
        this.txtDiemTKk.setText(jTable2.getValueAt(row, 4) + "");
        this.txtXepLoaii.setText((String) jTable2.getValueAt(row, 5));
        this.txtHocKyy.setText(lbhocky1.getText());
        String select = (String) jTable2.getValueAt(row, 0);
        System.out.println(select);
        jComboBox1.setSelectedItem(select);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int row = this.jTable3.getSelectedRow();
        this.txtTenMH.setText((String) jTable3.getValueAt(row, 1));
        //        this.txtTenMHh.setText((String) jTable1.getValueAt(row, 2));
        this.txtDiemGKk.setText(jTable3.getValueAt(row, 2) + "");
        this.txtDiemCKk.setText(jTable3.getValueAt(row, 3) + "");
        this.txtDiemTKk.setText(jTable3.getValueAt(row, 4) + "");
        this.txtXepLoaii.setText((String) jTable3.getValueAt(row, 5));
        this.txtHocKyy.setText(lbhocky2.getText());
        String select = (String) jTable3.getValueAt(row, 0);
        jComboBox1.setSelectedItem(select);

    }//GEN-LAST:event_jTable3MouseClicked

    private void btnNam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNam1ActionPerformed
        // TODO add your handling code here:
        lbhocky1.setText("1");
        lbhocky2.setText("2");
        HienThiNhieuBangDiem(lbMaSV.getText());
    }//GEN-LAST:event_btnNam1ActionPerformed

    private void btnNam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNam2ActionPerformed
        // TODO add your handling code here:
        lbhocky1.setText("3");
        lbhocky2.setText("4");
        HienThiNhieuBangDiem(lbMaSV.getText());
    }//GEN-LAST:event_btnNam2ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (KTma((String) jComboBox1.getSelectedItem(), Integer.valueOf(txtHocKyy.getText()))) {
            int ret = JOptionPane.showConfirmDialog(null, "Mã[" + jComboBox1.getSelectedItem() + "] Bạn có muốn xóa", "", JOptionPane.YES_NO_OPTION);
            if (ret == JOptionPane.NO_OPTION) {
                return;
            }
            try {
//            String sqldeletSV="delete  from sinhvien where masv='"+txtMaSV.getText()+"' ";
                String sqldeleteKQ = "delete from ketqua where mamh='" + jComboBox1.getSelectedItem() + "' and masv='" + lbMaSV.getText() + "'";
//            int y = statement.executeUpdate(sqldeleteKQ);
                int x = statement.executeUpdate(sqldeleteKQ);
                if (x >= 1) {
                    System.out.println(" Xóa khách hàng thành công");
                    HienThiNhieuBangDiem(masv);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNam5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNam5ActionPerformed
        // TODO add your handling code here:
        lbhocky1.setText("9");
        lbhocky2.setText("10");
        HienThiNhieuBangDiem(lbMaSV.getText());
    }//GEN-LAST:event_btnNam5ActionPerformed

    private void btmNam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmNam3ActionPerformed
        // TODO add your handling code here:
        lbhocky1.setText("5");
        lbhocky2.setText("6");
        HienThiNhieuBangDiem(lbMaSV.getText());
    }//GEN-LAST:event_btmNam3ActionPerformed

    private void btnNam4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNam4ActionPerformed
        // TODO add your handling code here:
        lbhocky1.setText("7");
        lbhocky2.setText("8");
        HienThiNhieuBangDiem(lbMaSV.getText());
    }//GEN-LAST:event_btnNam4ActionPerformed

    private void btnNam6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNam6ActionPerformed
        // TODO add your handling code here:
        lbhocky1.setText("11");
        lbhocky2.setText("12");
        HienThiNhieuBangDiem(lbMaSV.getText());
    }//GEN-LAST:event_btnNam6ActionPerformed
    private int global = 0;
    private PreparedStatement prestatement;
    private String masv;
    private DefaultTableModel dtm1 = null, dtm2 = null;
    private Vector<Object> vec1 = null, vec2 = null, vec3 = null, vec4 = null, vec5 = null, vec6 = null, vec7 = null, vec8 = null, vec9 = null, vec10 = null, vec11 = null, vec12 = null;
    public int hocky = 0;
    private float diemGK, diemCK, diemtkk;
    private Vector<Object> vecc[] = null;
    private ArrayList<JPanel> jp;
    private ResultSet result;
    private Connection con = null;
    private Statement statement = null;
    private DefaultTableModel dtmBangDiem;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmNam3;
    private javax.swing.JPanel btnButtonBTT;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNam1;
    private javax.swing.JButton btnNam2;
    private javax.swing.JButton btnNam4;
    private javax.swing.JButton btnNam5;
    private javax.swing.JButton btnNam6;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    public javax.swing.JLabel lbGioitinh;
    private javax.swing.JLabel lbHK1;
    private javax.swing.JLabel lbHK2;
    public javax.swing.JLabel lbHoten;
    public javax.swing.JLabel lbLop;
    public javax.swing.JLabel lbMaSV;
    public javax.swing.JLabel lbNgaysinh;
    public javax.swing.JLabel lbQueQuan;
    private javax.swing.JLabel lbhocky1;
    private javax.swing.JLabel lbhocky2;
    private javax.swing.JPanel pBTT;
    private javax.swing.JPanel pTren;
    private javax.swing.JPanel pTren_Phai;
    private javax.swing.JPanel pTren_Trai;
    private javax.swing.JPanel pTxtFieldBTT;
    private javax.swing.JTextField txtDiemCKk;
    private javax.swing.JTextField txtDiemGKk;
    private javax.swing.JTextField txtDiemTKk;
    private javax.swing.JTextField txtHocKyy;
    private javax.swing.JTextField txtTenMH;
    private javax.swing.JTextField txtXepLoaii;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnButtonBTT
     */
    public JPanel getPBTT() {
        return pBTT;
    }

    public void setPBTT(JPanel pBTT) {
        this.pBTT = pBTT;
    }

    public JLabel getLbMaSV() {
        return lbMaSV;
    }

    public void setLbMaSV(JLabel lbMaSV) {
        this.lbMaSV = lbMaSV;
    }
}
